server:
  port: 8001
#  #服务中心页面地址
spring:
  application:
#    应用名
    name: ad-gateway
 
eureka:
  client:
#    eureka服务器访问地址
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
#网关的前缀，非必需的，是网关的统一前缀
  prefix: /imooc
  routes:
    sponsor:
#匹配到path后 转发到应用名为 eureka-client-ad-sponsor 的微服务
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
#是否跳过前缀 false 不跳过前缀  样例：127.0.0.1:8000/imooc/ad-sponsor/create/adPlan
      strip-prefix: false